POST http://localhost:8000/digiext-api/v1/users/register
Content-Type: application/json

{
    "firstname": "Promethium",
    "lastname": "Rhenium",
    "email": "channelproteam@gmail.com",
    "phone": "08169544125",
    "password": "12345678",
    "confirm_password": "12345678"
}

###
PUT http://localhost:8000/digiext-api/v1/users/verify-otp
Content-Type: application/json

{
    "email": "channelproteam@gmail.com",
    "otp": ["d", "d", "1", "6"]
}